export const SETTINGS_PROVIDERS = [
  {
    id: 'openrouter',
    label: 'OpenRouter',
    link: 'https://openrouter.ai/keys',
    guide: 'https://openrouter.ai/docs/api-reference/authentication',
    hint: '实时读取 :free / free router，并排除收费、音频和安全工具模型',
  },
  {
    id: 'gemini',
    label: 'Google Gemini',
    link: 'https://aistudio.google.com/apikey',
    guide: 'https://ai.google.dev/gemini-api/docs/api-key',
    hint: '只显示当前免费层支持的 Flash / Flash-Lite 与 Gemma 型号',
  },
  {
    id: 'siliconflow',
    label: '硅基流动 SiliconFlow',
    link: 'https://cloud.siliconflow.cn/account/ak',
    guide: 'https://docs.siliconflow.cn/cn/userguide/quickstart',
    hint: '只显示平台明确提供的免费模型，试用赠金模型不会混入',
  },
  {
    id: 'cohere',
    label: 'Cohere',
    link: 'https://dashboard.cohere.com/api-keys',
    guide: 'https://docs.cohere.com/reference/about',
    hint: 'Trial Key 仅适合开发测试，模型共享较低的免费速率限制',
  },
  {
    id: 'huggingface',
    label: 'Hugging Face',
    link: 'https://huggingface.co/settings/tokens',
    guide: 'https://huggingface.co/docs/inference-providers',
    hint: '只显示上游标记为零价格的实时端点，普通按量模型会被排除',
  },
  {
    id: 'sensenova',
    label: 'SenseNova 商汤',
    link: 'https://platform.sensenova.cn',
    guide: 'https://platform.sensenova.cn',
    hint: '实时读取模型价格，只保留输入和输出价格都为零的文本模型',
  },
  {
    id: 'modelscope',
    label: 'ModelScope 魔搭',
    link: 'https://modelscope.cn/my/myaccesstoken',
    guide: 'https://modelscope.cn/docs/model-service/API-Inference/intro',
    hint: '免费调用受账号与平台配额限制，以模型服务接口返回为准',
  },
  {
    id: 'zhipu',
    label: '智谱 AI',
    link: 'https://open.bigmodel.cn/usercenter/apikeys',
    guide: 'https://open.bigmodel.cn/dev/howuse/introduction',
    hint: '只列入平台明确标记为免费的 Flash 型号',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    link: 'https://platform.deepseek.com/api_keys',
    guide: 'https://api-docs.deepseek.com',
    hint: '官方模型按量收费；试用赠金不算免费，因此不会加入目录',
  },
  {
    id: 'dashscope',
    label: '阿里百炼 DashScope',
    link: 'https://bailian.console.aliyun.com/?apiKey=1',
    guide: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key',
    hint: '限时试用额度不算免费，当前不会把百炼收费模型加入目录',
  },
  {
    id: 'cerebras',
    label: 'Cerebras',
    link: 'https://cloud.cerebras.ai/platform/keys',
    guide: 'https://inference-docs.cerebras.ai/quickstart',
    hint: '使用账号自带的开发者免费配额，额度与速率以控制台为准',
  },
  {
    id: 'nvidia',
    label: 'NVIDIA NIM',
    link: 'https://build.nvidia.com/settings/api-keys',
    guide: 'https://docs.api.nvidia.com/nim/reference/getting-started',
    hint: '使用 build.nvidia.com 开发者 API 的限速免费访问',
  },
  {
    id: 'mistral',
    label: 'Mistral AI',
    link: 'https://console.mistral.ai/api-keys',
    guide: 'https://docs.mistral.ai/getting-started/quickstart/',
    hint: '使用 Experiment 开发计划的限速免费访问，以账号控制台为准',
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare Workers AI',
    link: 'https://dash.cloudflare.com/profile/api-tokens',
    guide: 'https://developers.cloudflare.com/workers-ai/get-started/rest-api/',
    hint: '需要 API Token 和 Account ID；免费分配量用尽后请求会失败',
  },
  {
    id: 'github',
    label: 'GitHub Models',
    link: 'https://github.com/settings/tokens',
    guide: 'https://docs.github.com/en/github-models/prototyping-with-ai-models',
    hint: '所有账号都有用于原型开发的限速免费用量，付费使用需另行启用',
  },
] as const;
